settings:
  username: "IgorGakhov"
  commit_msg: ":zap: Update README with the recent activity"
  max_lines: 10
  readme_file: "./README.md"

messages:
  comments: ":speech_balloon: Commented on {ID} in {REPO}"
  issue_opened: ":exclamation: Opened issue {ID} in {REPO}"
  issue_closed: ":heavy_check_mark: Closed issue {ID} in {REPO}"
  pr_opened: ":muscle: Opened PR {ID} in {REPO}"
  pr_closed: ":x: Closed PR {ID} in {REPO}"
  pr_merged: ":tada: Merged PR {ID} in {REPO}"
  push: ":arrow_up: Pushed {AMOUNT} commit(s) to {REPO}"
  create_repo: ":notebook_with_decorative_cover: Created new repository {REPO}"
  fork_repo: ":trident: Forked {FORK} from {REPO}"
  wiki_create: ":book: Created new wiki page {WIKI} in {REPO}"
  added_member: ":handshake: Became collaborator on {REPO}"
  changes_approved: ":+1: Approved {ID} in {REPO}"
  changes_requested: ":red_circle: Requested {AMOUNT} change(s) in {ID} in {REPO}"
  new_release: ":v: Released {ID} in {REPO}"
  new_star: ":star: Starred {REPO}"
