name: Update README

on:  
  schedule:
    # Runs at the end of every day.
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add activity to readme
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
